AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB tables for MSC Evaluate application'

Resources:
  # Users Table
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: msc-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Application
          Value: MSC-Evaluate
        - Key: Environment
          Value: Production

  # Templates Table
  TemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: msc-templates
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: template_id
          AttributeType: S
        - AttributeName: subject
          AttributeType: S
        - AttributeName: course
          AttributeType: S
      KeySchema:
        - AttributeName: template_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: subject-course-index
          KeySchema:
            - AttributeName: subject
              KeyType: HASH
            - AttributeName: course
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Application
          Value: MSC-Evaluate
        - Key: Environment
          Value: Production

  # Quiz Results Table
  QuizResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: msc-quiz-results
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: result_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: template_id
          AttributeType: S
        - AttributeName: completed_at
          AttributeType: S
      KeySchema:
        - AttributeName: result_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: completed_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: template-id-index
          KeySchema:
            - AttributeName: template_id
              KeyType: HASH
            - AttributeName: completed_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Application
          Value: MSC-Evaluate
        - Key: Environment
          Value: Production

Outputs:
  UsersTableName:
    Description: 'Name of the Users DynamoDB table'
    Value: !Ref UsersTable
    Export:
      Name: !Sub '${AWS::StackName}-UsersTable'

  TemplatesTableName:
    Description: 'Name of the Templates DynamoDB table'
    Value: !Ref TemplatesTable
    Export:
      Name: !Sub '${AWS::StackName}-TemplatesTable'

  QuizResultsTableName:
    Description: 'Name of the Quiz Results DynamoDB table'
    Value: !Ref QuizResultsTable
    Export:
      Name: !Sub '${AWS::StackName}-QuizResultsTable'